### ISSUE TITLE
想爬全部数据需要vip会员

### ISSUE THREAD

**Issue by Kevan807680925** [lubosson/webinfo-crawler#1]
想爬全部数据需要vip会员。。。。

**Comment by The-WindRises** [comment]
vip会员的AUTHORIZATION和X_AUTH_TOKEN怎么拿？

**Comment by bouxin** [comment]
> vip会员的AUTHORIZATION和X_AUTH_TOKEN怎么拿？

抓包天眼查小程序app

**Comment by bouxin** [comment]
> 想爬全部数据需要vip会员。。。。

如果走html解析的方式话得绕过cookie登陆验证，cookie有规律但比较难找。
走api目测是可以的

**Comment by Warriorwithdreams** [comment]
小程序的接口为什么我用fiddler抓的时候是加密了不给返回信息呢？楼主大大是用什么抓包软件的？

**Comment by bouxin** [comment]
> 小程序的接口为什么我用fiddler抓的时候是加密了不给返回信息呢？楼主大大是用什么抓包软件的？

抓包用的Charles。没有返回信息，试试把请求头伪装全一点

**Comment by Warriorwithdreams** [comment]
但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？

**Comment by bouxin** [comment]
> 但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？

用Android 版本小于6.0的手机抓包小程序，抓到的网络包请求头里有这两个参数，今晚10点我会维护一下

**Comment by Warriorwithdreams** [comment]
> > 但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？
> 
> 用Android 版本小于6.0的手机抓包小程序，抓到的网络包请求头里有这两个参数，今晚10点我会维护一下

IOS手机可以吗？目前手上只有IOS手机

**Comment by Warriorwithdreams** [comment]
> > 但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？
> 
> 用Android 版本小于6.0的手机抓包小程序，抓到的网络包请求头里有这两个参数，今晚10点我会维护一下

楼主大大，可以给一个X_AUTH_TOKEN和AUTHORIZATION吗？

**Comment by bouxin** [comment]
> > > 但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？
> > 
> > 
> > 用Android 版本小于6.0的手机抓包小程序，抓到的网络包请求头里有这两个参数，今晚10点我会维护一下
> 
> 楼主大大，可以给一个X_AUTH_TOKEN和AUTHORIZATION吗？

晚上10点我更新，然后你拉一下就好了，我只知道ipx 和ip8不可以，其他的不太清楚。关于ssl证书是因为高版本系统对ssl授权方式发生了变化，所以高版本系统的手机ssl就算设置了信任仍会验证失败（用户级别和系统级别，高版本只认可系统级别的），可以root手机手动信任证书，也可以使用低版本的系统

**Comment by Warriorwithdreams** [comment]
> > > > 但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？
> > > 
> > > 
> > > 用Android 版本小于6.0的手机抓包小程序，抓到的网络包请求头里有这两个参数，今晚10点我会维护一下
> > 
> > 
> > 楼主大大，可以给一个X_AUTH_TOKEN和AUTHORIZATION吗？
> 
> 晚上10点我更新，然后你拉一下就好了，我只知道ipx 和ip8不可以，其他的不太清楚。关于ssl证书是因为高版本系统对ssl授权方式发生了变化，所以高版本系统的手机ssl就算设置了信任仍会验证失败（用户级别和系统级别，高版本只认可系统级别的），可以root手机手动信任证书，也可以使用低版本的系统

好的，谢谢楼主！不知道可以不可以添加一个主要人员或股东信息的接口抓取，哈哈，没有也没关系，我自己去试试

**Comment by bouxin** [comment]
> > > > > 但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？
> > > > 
> > > > 
> > > > 用Android 版本小于6.0的手机抓包小程序，抓到的网络包请求头里有这两个参数，今晚10点我会维护一下
> > > 
> > > 
> > > 楼主大大，可以给一个X_AUTH_TOKEN和AUTHORIZATION吗？
> > 
> > 
> > 晚上10点我更新，然后你拉一下就好了，我只知道ipx 和ip8不可以，其他的不太清楚。关于ssl证书是因为高版本系统对ssl授权方式发生了变化，所以高版本系统的手机ssl就算设置了信任仍会验证失败（用户级别和系统级别，高版本只认可系统级别的），可以root手机手动信任证书，也可以使用低版本的系统
> 
> 好的，谢谢楼主！不知道可以不可以添加一个主要人员或股东信息的接口抓取，哈哈，没有也没关系，我自己去试试

有空了会考虑加上

**Comment by Warriorwithdreams** [comment]
> > > > > > 但是我现在用楼主的X_AUTH_TOKEN和AUTHORIZATION认证过期了，我想去重新配置一下这两个参数，我应该怎么操作呢？
> > > > > 
> > > > > 
> > > > > 用Android 版本小于6.0的手机抓包小程序，抓到的网络包请求头里有这两个参数，今晚10点我会维护一下
> > > > 
> > > > 
> > > > 楼主大大，可以给一个X_AUTH_TOKEN和AUTHORIZATION吗？
> > > 
> > > 
> > > 晚上10点我更新，然后你拉一下就好了，我只知道ipx 和ip8不可以，其他的不太清楚。关于ssl证书是因为高版本系统对ssl授权方式发生了变化，所以高版本系统的手机ssl就算设置了信任仍会验证失败（用户级别和系统级别，高版本只认可系统级别的），可以root手机手动信任证书，也可以使用低版本的系统
> > 
> > 
> > 好的，谢谢楼主！不知道可以不可以添加一个主要人员或股东信息的接口抓取，哈哈，没有也没关系，我自己去试试
> 
> 有空了会考虑加上

好的，非常感谢分享

**Comment by xiehaisen1986** [comment]
大佬能不能加一个按地区爬的功能

**Comment by xiehaisen1986** [comment]
还有重新爬的话数据库里的 数据会不会重复呢

**Comment by bouxin** [comment]
> 还有重新爬的话数据库里的 数据会不会重复呢

不会重复，uk = credit_code&register_code
