### ISSUE TITLE
请问怎么抓包最新版电脑端小程序呢？

### ISSUE THREAD

**Issue by yuanyang111** [lubosson/webinfo-crawler#24]

**Comment by fubostudy** [comment]
mac 的话使用 charles这个软件，设置完了后在电脑端通过天眼查微信小程序抓取。

**Comment by yuanyang111** [comment]
好滴 谢谢您~还想问问看您知道怎么抓取天眼查中的企业关系图谱的信息么

**Comment by fubostudy** [comment]
> 好滴 谢谢您~还想问问看您知道怎么抓取天眼查中的企业关系图谱的信息么
你要不加一下我的联系方式 vx：b1359453864 我们交流一下 我也在弄这个

**Comment by fubostudy** [comment]
不清楚哎 我也不太会，都是向作者请教的😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yuanyang111 ***@***.***&gt;
发送时间: 2022年4月8日 12:07
收件人: bouxin/company-crawler ***@***.***&gt;
抄送: ferry_xie ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [bouxin/company-crawler] 请问怎么抓包最新版电脑端小程序呢？ (Issue #24)





 
好滴 谢谢您~还想问问看您知道怎么抓取天眼查中的企业关系图谱的信息么
