### ISSUE TITLE
天眼查小程序更新加密了？

### ISSUE THREAD

**Issue by fubostudy** [lubosson/webinfo-crawler#29]
作者您好！不知道是不是天眼查更新加密了，我今天抓取的时候用抓包软件看到下面的提示，现在已经爬取不了了，这种情况是不是得伪造识别码，把小程序反编译出来，然后破解？求请问作者可以更新程序吗？如果可以的话，万分感谢🙏！祝好！

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49436908/205435917-cc71c076-ebe9-485f-b410-66e31b0ac263.png">

**Comment by bouxin** [comment]
换中国大陆的IP池

**Comment by harborq** [comment]
这个是人家屏蔽了国外的访问，你换成大陆的ip访问就不会出现这种问题

**Comment by fubostudy** [comment]
> 换中国大陆的IP池

关了代理，换了代理池，还是不行，作者你这边是还可以运行吗🙏

**Comment by fubostudy** [comment]
> 关了代理，换了代理池，还是不行，作者你这边是还可以运行吗🙏



> 这个是人家屏蔽了国外的访问，你换成大陆的ip访问就不会出现这种问题

关了代理，换了代理池，还是不行，你这边是还可以运行吗🙏

**Comment by bouxin** [comment]
> > 换中国大陆的IP池
> 
> 关了代理，换了代理池，还是不行，作者你这边是还可以运行吗🙏

### 使用本机系统代理
1. 打开任意浏览器，检测出口IP是否被风控[点击进行IP检测](https://www.tianyancha.com/search?key=完美世界)。如果不能正常访问，则出口网络已被风控，风控等级大概为3天，7天，1月，3月，6月，1年、5年，永封。一般情况下，触发风控不会被永封，经验来说通常在3天至3个月不等的范围内。
2. 如IP访问正常，检测本机网卡接口代理情况。Mac电脑查看路径：设置->网络->WiFI->高级->代理；Windows电脑查看路径：设置->网络->代理&VPN。检测代理是否正常，[点击检测代理](https://whatismyipaddress.com)

如上述步骤均无异常，不使用代理的情况下修改util.httpclient文件下Request类:
```
    ENABLE_PROXY = False
    def get(self, **kwargs):
        p = proxy() if ENABLE_PROXY and self.proxy else None
        resp = requests.get(self.url, params=self.params, verify=False, proxies=p, **kwargs)
        if resp and resp.status_code == 200:
            self.data = resp.text
        else:
            logging.warning(resp)
```

### 使用IP代理池
1. 检测代理池IP，打开terminal工具:
```
# 如果使用https则采用https协议头，ip.SB为检测地址
curl --proxy "http://ip:port" ip.SB
```
2. 如代理不正常，请尝试更换IP源，修改util.httpclient文件下Request类：
```
    ENABLE_PROXY = True
    def get(self, **kwargs):
        p = proxy() if ENABLE_PROXY and self.proxy else None
        resp = requests.get(self.url, params=self.params, verify=False, proxies=p, **kwargs)
        if resp and resp.status_code == 200:
            self.data = resp.text
        else:
            logging.warning(resp)
```

**Comment by fubostudy** [comment]
![Uploading image.png…]()
是不是因为接口换了？我用了这个接口挂不挂代理都可以访问，用之前的接口怎么换代理都还是不行，作者你这边现在的版本是可以爬取的吗？

**Comment by fubostudy** [comment]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/49436908/207158613-8a70136f-419a-4acd-95a5-7a0d257db9b4.png">

**Comment by bouxin** [comment]
> ![Uploading image.png…]()
> 
> 是不是因为接口换了？我用了这个接口挂不挂代理都可以访问，用之前的接口怎么换代理都还是不行，作者你这边现在的版本是可以爬取的吗？

我可以访问的

**Comment by fubostudy** [comment]
ook，非常感谢作者，那我这边再调试一下看看，感谢！

**Comment by fubostudy** [comment]
作者 您好！我这边找了几个人都测试了一下，无论加不加代理都用不了。但是我发的那个新接口无论代理不代理，都可以爬取。 你这边可以运行是前几天测试的吗？如果现在也不行了的话，可以麻烦您有空的时候更新一下程序吗？感谢了！以及现在疫情严重，最近注意多休息啊🙏

**Comment by bouxin** [comment]
感谢关心，我刚运行测试调用100次接口没有受到影响，大概率是你的public IP受到风控了。我看了你给出的新API，有可能天眼查对接口做了升级。

**Comment by fubostudy** [comment]
> 感谢关心，我刚运行测试调用100次接口没有受到影响，大概率是你的public IP受到风控了。我看了你给出的新API，有可能天眼查对接口做了升级。

好的，感谢🙏 我换台电脑再试试看

**Comment by fubostudy** [comment]
> 感谢关心，我刚运行测试调用100次接口没有受到影响，大概率是你的public IP受到风控了。我看了你给出的新API，有可能天眼查对接口做了升级。

同时，可以请问一下作者，这个如果每天的token达到上限后被限制了，应该在哪里修改让其自动换token，而不需要手动换token呢？这个修改起来麻烦吗？谢谢！

**Comment by bouxin** [comment]
> 

每日token上限我不太清楚，没有测试过。

关于token功能：
     可以通过使用多个微信登陆天眼查，整理一个token池，设计一个轮询算法，每次去token池获取一个可用的token。


项目有个未完成的功能wechat_auth.py，该功能提供扫码加入token池和扫码提取token。（限于维护精力有限，未完成）

我想可能在未来的3个月内我会再维护一次该项目同时完成该功能。

**Comment by fubostudy** [comment]
> > 
> 
> 每日token上限我不太清楚，没有测试过。
> 
> 关于token功能： 可以通过使用多个微信登陆天眼查，整理一个token池，设计一个轮询算法，每次去token池获取一个可用的token。
> 
> 项目有个未完成的功能wechat_auth.py，该功能提供扫码加入token池和扫码提取token。（限于维护精力有限，未完成）
> 
> 我想可能在未来的3个月内我会再维护一次该项目同时完成该功能。

太棒了👍 👍👍 等更新，谢谢大佬！

**Comment by harborq** [comment]
> > 
> 
> 每天token上限我不太清楚，没有测试过。
> 
> 关于token功能： 可以通过使用多个微信登陆天眼查，整理一个token池，设计一个轮询算法，每次去token池获取一个可用的token。
> 
> 项目有一个未完成的功能wechat_auth.py，该功能提供扫码加入token池和扫码提取token。（限于维护精力有限，未完成）
> 
> 我想可能在未来的 3 个月内我会再次维护一次该项目项目同时完成该功能。

期待作者再一次维护 👍 👍👍

**Comment by harborq** [comment]
> > 
> 
> 每日token上限我不太清楚，没有测试过。
> 
> 关于token功能： 可以通过使用多个微信登陆天眼查，整理一个token池，设计一个轮询算法，每次去token池获取一个可用的token。
> 
> 项目有个未完成的功能wechat_auth.py，该功能提供扫码加入token池和扫码提取token。（限于维护精力有限，未完成）
> 
> 我想可能在未来的3个月内我会再维护一次该项目同时完成该功能。

你好，作者；咱们这个有没有一个可以交流的群组，例如：微信、QQ群等方式
