### ISSUE TITLE
刚更新这个搜不到数据

### ISSUE THREAD

**Issue by xiehaisen1986** [lubosson/webinfo-crawler#3]
05/02/2019 12:52:39 crawler.py[line:45] INFO 开始搜索关键字[火锅]
05/02/2019 12:52:41 crawler.py[line:84] ERROR [tyc]api error, warn-无数据
05/02/2019 12:52:41 crawler.py[line:47] INFO 开始解析
05/02/2019 12:52:42 crawler.py[line:125] INFO no companies available
05/02/2019 12:52:42 crawler.py[line:49] INFO 数据已保存
05/02/2019 12:52:42 crawler.py[line:50] INFO 结束

**Comment by bouxin** [comment]
日志-没搜到数据啊

**Comment by bouxin** [comment]
企查查我还没写完
