### ISSUE TITLE
【bug贴】如发现bug欢迎在这里提出

### ISSUE THREAD

**Issue by bouxin** [lubosson/webinfo-crawler#7]

**Comment by einherjarcai** [comment]
你好，请问天眼查的相关链接和请求验证头，token这是是怎么获取的？方便留个联系方式吗？向您请教一下

**Comment by Warriorwithdreams** [comment]
我又来求更新了，现在AUTHORIZATION和X_AUTH_TOKEN已经失效了，我手上也没有安卓手机可以用来更新AUTHORIZATION和X_AUTH_TOKEN，辛苦楼主大大了

**Comment by bouxin** [comment]
IOS系统也可以抓包😓，等我更新的话可能要这周五了，这两天有点忙  @Warriorwithdreams

**Comment by Warriorwithdreams** [comment]
IOS系统应该怎么抓取呢？

**Comment by lubosson** [comment]
> IOS系统应该怎么抓取呢？

[iOS应该怎么抓包](https://www.google.com/search?safe=active&source=hp&ei=V-3tXPPzNZ2S0PEPj-CliAE&q=Charles+%E6%8A%93%E5%8C%85iOS&oq=Charles+%E6%8A%93%E5%8C%85iOS&gs_l=psy-ab.12...0.0..4253...0.0..0.0.0.......0......gws-wiz.)

**Comment by bouxin** [comment]
@Warriorwithdreams [iOS应该怎么抓包](https://www.google.com/search?safe=active&source=hp&ei=V-3tXPPzNZ2S0PEPj-CliAE&q=Charles+%E6%8A%93%E5%8C%85iOS&oq=Charles+%E6%8A%93%E5%8C%85iOS&gs_l=psy-ab.12...0.0..4253...0.0..0.0.0.......0......gws-wiz.)
