### ISSUE TITLE
天眼查爬虫不能用了，现在需要登录才行。

### ISSUE THREAD

**Issue by morning71** [lubosson/webinfo-crawler#8]
可能要在headers里添加cookie使用

**Comment by bouxin** [comment]
请帖401的代码

**Comment by hustmib** [comment]
能够组个群，交流下？

我最开始不用登陆，直接 authorization 和 token 跑了一个月。

然后就不让访问了，显示信息见下面的提示

用 @lubosson提供的token和authorization 可以顺畅跑。

初浅的得个结论就是：每个token和authorization都是有寿命的。

对了，小程序里面，headers里面没有 cookies，我检查过了。

希望能在这个帖子上保持交流

**Comment by hustmib** [comment]
![image](https://user-images.githubusercontent.com/8804522/62298191-1b2c4380-b4a5-11e9-834b-a1bf38a2bf6b.png)

**Comment by BoysFight** [comment]
我这儿运行直接报403错误，尝试修改了UA貌似没有效果，是现在不能使用了还是需要其它特殊设置呢？

PS：我直接在浏览器里访问代码中的url，出现下边的提示：

> 系统检测到您非人类行为，己被禁止访问天眼查，若有疑问请联系官方qq群 515982002
> IP地址：116.25.147.83访问时间：2019-08-03
> 欢迎访问tianyancha.com.cn数据接口平台，免费调用，名额有限

**Comment by hustmib** [comment]
@boysFight，我个人感觉，你这个应该是header没有弄好，被禁掉了。。

anyway，我想说的是，每个token都似乎有次数限制。

**Comment by bouxin** [comment]
@hustmib 可能是不允许多端登陆，保持单点登陆或共用token

**Comment by bouxin** [comment]
@BoysFight IP都给你贴出来了-黑名单了啊，访问走代理就可以了

**Comment by bouxin** [comment]
我感觉限制次数和异常访问是通过IP来统计的，cookie和token可能是在访问的时候简单的过滤一下访问请求，有个专门的访问日志分析每个请求的IP，这才是block的关键

**Comment by hustmib** [comment]
这个怎么破解@lubosson

**Comment by hustmib** [comment]
我没有拦截到日志这个包，

**Comment by bouxin** [comment]
> 这个怎么破解@lubosson

IP代理

**Comment by jessiecuicui** [comment]
楼主，代码可以运行，但是跑了几个小时后就不能用了提示未登录，请问token，验证头等信息如何获取呢？我抓包也看不到呢，能不能加个好友请教一下

**Comment by bouxin** [comment]
> 楼主，代码可以运行，但是跑了几个小时后就不能用了提示未登录，请问token，验证头等信息如何获取呢？我抓包也看不到呢，能不能加个好友请教一下

你用啥抓的啊，http请求头里有authorization token的，要分不清楚，就把抓到的所有请求头都放到你的请求里

**Comment by Python-time** [comment]
报401 ，是不是令牌失效了 请求代码如下
{"state":"warn","message":"must login","special":"","vipMessage":"","isLogin":0,"data":null}

**Comment by bouxin** [comment]
恩令牌失效，建议抓取自己账号的令牌

**Comment by Python-time** [comment]
@lubosson 是抓的app 还是 pc 端的。

**Comment by bouxin** [comment]
微信小程序

**Comment by Python-time** [comment]
@lubosson  好的谢谢

**Comment by Dr1zzt** [comment]
@lubosson 楼主那个天眼查小程序的抓包还能抓取到token吗？我在本地尝试，请求中好像没有传有token这些东西呀？

**Comment by chenqigao** [comment]
楼主，问一下抓取参数可以在增加？比如说加一个搜索条件 加“”企业名“” 或者“成立日期从晚到早”。是在crawler.py中的
payload = {
            "pageNum": 1,
            "pageSize": 20,
            "sortType": 3
#           "companyType": 1
        }
设置？

**Comment by bouxin** [comment]
需要抓包确认，我没有分析过所有入参

**Comment by Blivrig** [comment]
> 能够组个群，交流下？
> 
> 我最开始不用登陆，直接授权和token跑了一个月。
> 
> 然后就不让访问了，显示信息见下面的提示
> 
> 用@lubosson提供的令牌和授权可以顺畅跑。
> 
> 初浅的得个个体就是：每个令牌和授权都是有寿命的。
> 
> 对了，小程序里面，headers里面没有cookie，我检查过了。
> 
> 希望能在这个帖子上保持交流
不如使用app的
